name: 🎨 » color check

on:
  pull_request:
    paths:
      - "icons/*.svg"

permissions:
  contents: read

jobs:
  color-check:
    name: SVG Color Check
    runs-on: ubuntu-latest
    env:
      TARGET_BRANCH: ${{ github.event.pull_request.base.ref }}

    steps:
      - name: 📥 Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: 🔄 Fetch target branch
        run: |
          git fetch origin $TARGET_BRANCH

      - name: 🎨 Check colors
        run: |
          svgFiles=$(git diff origin/$TARGET_BRANCH --diff-filter=ACMRTUX  --name-only | grep '.svg$')
          npx svg-color-linter --config material-colors.yml ${svgFiles}
